### ISSUE TITLE
Ego motion compensation

### ISSUE THREAD

**Issue by TheCodez** [TheCodez/dynamic-occupancy-grid-map#10]
Using a 2d ring buffer like structure would be the fastest way.
Just shifting the grid cells is probably the easiest to implement.

**Comment by TheCodez** [comment]
Implemented using grid shifting in https://github.com/TheCodez/dynamic-occupancy-grid-map/commit/4a99b9fc25eb50944f1eec8bbf842cb6847248bd

Performance is good for now.

**Comment by cbachhuber** [comment]
That looks good, at least as far as I can tell from reading the code. You assume that the measurement grid is always in the correct position, right?

General comment: I can see no tests (also not in the demo application) for this new code. I guess you did some tests during development.
Still, in particular in collaborative projects, tests help other people understand what you're doing and do not require blind trust to accept what you write.

I understand that adding a test for this would slow you down now; but in the long run, you avoid nasty [errors](https://github.com/TheCodez/dynamic-occupancy-grid-map/commit/f58ed5a028433519d32e2a4765574f11e1499509) and save time. A test doesn't have to be a super-detailed gtest unit test; a demo application that shows that things are working as expected is also fine for a start.

This is my recommendation and preference. The decision about your way of development is of course still up to you :+1:

**Comment by TheCodez** [comment]
Yes I assume that when a new pose is set, the new measurement grid was taken at that pose.

Agree, only I know whether or not the feature works. I did some testing in the demo project to see if it works as desired. Ideally this would be implemented in the simulator (should be really easy to do actually) or tested with real data e.g. KITTI dataset.

I will add a test case for this to test a few basic things (testing the grid map arrays is a harder) 👍

Generally speaking, I want to add some tests for the particle filter where possible at some point, but it's not a high priority currently.

**Comment by TheCodez** [comment]
Test case added in https://github.com/TheCodez/dynamic-occupancy-grid-map/commit/69cfa3402df1d0cbd16c89e9a6695e3ddd593be6
