### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by cbachhuber** [TheCodez/dynamic-occupancy-grid-map#15]
I cannot find systematic code formatting in this project yet. I (among most programmers ;) ) like well-formatted code, that makes it easy to read code. If you agree to use automated code formatting at this stage, I would suggest the widely used [clang-format](https://clang.llvm.org/docs/ClangFormat.html). Clang-format also [supports formatting CUDA](https://reviews.llvm.org/D42589) files.

I have applied clang-format to this repository in [this branch](https://github.com/cbachhuber/dynamic-occupancy-grid-map/tree/use-clang-format/dogm), feel free to check whether you like the style. In the branch, I have also added [instructions on how to use clang-format for formatting](https://github.com/cbachhuber/dynamic-occupancy-grid-map/tree/use-clang-format#contributing).

**Comment by TheCodez** [comment]
I completely agree with you and clang-format would also be my formatter of choice.

Briefly checking out your branch there are a few things I would like to have differently, namely:

1. Curly brackets should be on the next line.
2. Add a space after `if`, `else`, `for` and `while`.

Other than that I'm fine with this change 👍

**Comment by cbachhuber** [comment]
Cool, I'll implement your suggestions and open a PR!

**Comment by cbachhuber** [comment]
Thanks for applying clang-format! I just wanted to open a PR that adds code in `demo/main.cpp`, and I saw that this file is not yet formatted. Is there a reason why you didn't do that yet?
