### ISSUE TITLE
Evaluate accuracy

### ISSUE THREAD

**Issue by TheCodez** [TheCodez/dynamic-occupancy-grid-map#23]
Evaluate performance and avoid regressing.

Use DBSCAN to extract clusters and calculate mean velocity of those clusters to compare them with the ground truth.

**Comment by cbachhuber** [comment]
I just thought about how this could look like. What do you think of the below interface?

```c++
// demo/simulator.h
// ...

struct SimulationStep
{
    std::vector<Vehicle> vehicles;
    std::vector<float> measurements;
}
// ...

struct Simulator
{
    // This function now returns also vehicle ground truth data; needed for evaluation
    std::vector<SimulationStep> update(int steps, float dt)
    //...

}
// ...
```

```c++
// demo/main.cpp
// ...

int main(int argc, const char** argv)
// ...

std::vector<SimulationStep> sim_data = simulator.update(10, delta_time); 
PrecisionEvaluator precision_evaluator{sim_data};
for (int i = 0; i < sim_data.size(); i++)
{
    grid_map.updateMeasurementGrid(sim_data[i].measurements.data(), sim_data[i].measurements.size());
    // ...

    bool print_current_precision = true;  // This is just here for explanatory reasons
    precision_evaluator.evaluateAndStoreStep(i, grid_map, print_current_precision);
    // ...

}

precision_evaluator.printSummary();
// ...
```

**Comment by TheCodez** [comment]
@cbachhuber 
Yes that looks good 👍 

I made you a little showcase of how to measure the velocity of only one object (for multiple objects we need a clustering algorithm of course).
https://github.com/TheCodez/dynamic-occupancy-grid-map/tree/test_velocity_estimation

**Comment by cbachhuber** [comment]
Perfect, thanks a bunch for that! 

I will start by evaluating existing DBSCAN (seems to be a very suitable algorithm, great suggestion!) libraries, maybe we can use one of them. If they are insufficient, I'll implement DBSCAN (probably copypaste large parts from existing code ;) ).

**Comment by TheCodez** [comment]
No need to do that, I created my own version today using the paper :)

**Comment by cbachhuber** [comment]
Nice! :+1:

**Comment by TheCodez** [comment]
I integrated DBSCAN into the codebase. It's all really hacky at the moment and at the wrong places, but it might be something you can work with :)

**Comment by cbachhuber** [comment]
Thank you once more! That makes my task much, much simpler.

Under Linux, it did not compile, I had to [fix two things](https://github.com/cbachhuber/dynamic-occupancy-grid-map/commit/6a66a4995c1503db54cbf3fb708e9b3e9328bce0). Posting this because the solutions might be relevant to you :)

I also [fixed the parameters](https://github.com/TheCodez/dynamic-occupancy-grid-map/commit/c530ce9f489280a1232c00cb68d3d4366fcc5227) to include points with a maximum distance of 3 (cells), and a minimum cell count of 5. With that, I'm getting robust performance.

Now I'll get to work, which is mainly tidying up and comparing your result with the ground truth.

**Comment by cbachhuber** [comment]
For assigning clusters to ground truth vehicles, I wanted to utilize locations. See pseudocode: 

```
1. For each cluster, compute mean location in addition to mean velocity
2. Compare the cluster location to the ground truth vehicles, find best match
3. Compute error between cluster velocity and ground truth vehicle velocity
```

The cluster locations also seem to require a coordinate transformation. This is the output of [my branch](https://github.com/cbachhuber/dynamic-occupancy-grid-map/tree/evaluate-performance), which currently has one vehicle with velocity vector (-5,20):
```
### DOGM initialization took: 1403 ms ###

### Iteration took: 167 ms ###
######  Saving result  #######
##############################
### Iteration took: 152 ms ###
######  Saving result  #######
##############################

Ground Truth: vel: -5 20, pos: 45 24
Est. values: vel: 1.6 15 , pos: 24 26

### Iteration took: 136 ms ###
######  Saving result  #######
##############################

Ground Truth: vel: -5 20, pos: 44 26
Est. values: vel: 1.7 18 , pos: 23 24

### Iteration took: 131 ms ###
######  Saving result  #######
##############################

Ground Truth: vel: -5 20, pos: 44 28
Est. values: vel: 1.7 19 , pos: 23 22

### Iteration took: 140 ms ###
######  Saving result  #######
##############################

Ground Truth: vel: -5 20, pos: 44 30
Est. values: vel: 1.7 19 , pos: 22 20

### Iteration took: 137 ms ###
######  Saving result  #######
##############################

Ground Truth: vel: -5 20, pos: 43 32
Est. values: vel: 1.7 19 , pos: 22 18

### Iteration took: 166 ms ###
######  Saving result  #######
##############################

Ground Truth: vel: -5 20, pos: 42 34
Est. values: vel: 1.8 20 , pos: 21 16

### Iteration took: 154 ms ###
######  Saving result  #######
##############################

Ground Truth: vel: -5 20, pos: 42 36
Est. values: vel: 1.8 20 , pos: 21 14

### Iteration took: 154 ms ###
######  Saving result  #######
##############################

Ground Truth: vel: -5 20, pos: 42 38
Est. values: vel: 1.8 20 , pos: 20 12

### Iteration took: 176 ms ###
######  Saving result  #######
##############################

Ground Truth: vel: -5 20, pos: 41 40
Est. values: vel: 1.8 20 , pos: 20 10
```

I see that the position difference over the entire simulation time is correct, except for the sign: x-position changes by 4 units in both ground truth and estimation, y-position by 16 units. So we seem to be almost there, but some offset transform seems to be missing. Since you have developed those parts, could you give me some guidance here?

**Comment by TheCodez** [comment]
Thanks you for the great work implementing this 👍 
I was thinking of the exact same algorithm to match estimation and ground truth.

To cite the [paper](https://arxiv.org/pdf/1605.02406.pdf)
"The x-component of the estimated velocity is aligned to the
longitudinal axis of the test vehicle."
I guess this is needed to get the correct velocity estimation (I don't know how to do that though).

About the position correction. The polar coordinates are mapped to cartesian space using the texture mapping prodecure. I assume it's not a real 1:1 mapping that's why using the math formulas to convert the points isn't working.
I try to get that working, that's a real blocker for the matching process.

**Comment by cbachhuber** [comment]
> To cite the paper
"The x-component of the estimated velocity is aligned to the
longitudinal axis of the test vehicle."
I guess this is needed to get the correct velocity estimation (I don't know how to do that though).

In this paragraph, the authors are only referring to the Segway scenario. In this scenario, the Segway directly drives towards the sensor, so the x-component of the estimated velocity is, per scenario definition, aligned to the Segway's longitudinal axis. Do you agree?

Thanks for looking into this issue. Don't stress yourself about this; I'll either go a day (or a couple of days) without working on this project, or I'll find something else that can be done in here ;)

**Comment by TheCodez** [comment]
Ah thank you for the explanation. 
Whats bugging me is that I'm not really sure if the velocity estimation is wrong or if it's some kind of conversion problem.

**Comment by TheCodez** [comment]
About the position, by testing I found some formulas which work quite well (mathematically correct of course...not :grin:)

You should add half the width to the ground truth x to get the center pos
```
std::cout << "\nGround Truth: vel: " << vehicle.vel[0] << " " << vehicle.vel[1]
                          << ", pos: " << vehicle.pos[0] + vehicle.width / 2.0f << " " << vehicle.pos[1] << "\n";
```

This is the other formula:
```
mean_y_pos = hypotf(mean_x_pos, mean_y_pos);
mean_x_pos *= 2.0f;
```

It works for some objects and could be used as a starting point until a correct solution is found.

**Comment by cbachhuber** [comment]
> Whats bugging me is that I'm not really sure if the velocity estimation is wrong or if it's some kind of conversion problem (the y-velocity is always quite close actually).

I also think think there's a conversion problem. I've just looked at the `grid_img` of a few simple scenarios (vehicle with either only x-velocity or only y-velocity). Observations:
- A vehicle with only x-velocity moves in the final `grid_img` on a circle with center in the sensor
- A vehicle with only y-velocity moves in the final  `gird_img`  on a straight line stemming from the sensor. Direction is determined by the initial point of the vehicle.

To me, this looks like you transform the cartesian simulation grid directly to a polar coordinate system (CS). Instead of a forward cartesian to polar CS transformation, I think we need an inverse one. Such that a vehicle moving straight in x-direction in the simulation CS moves on kind of a parabol in the polar CS: it is closest directly in front of the sensor, and has an increasing radial distance when it is on either side (see the quickly sketched image below). What are your thoughts on this?

![cst](https://user-images.githubusercontent.com/27212661/79063323-40fb2080-7ca1-11ea-8b24-df482734c1d8.jpg)

**Comment by cbachhuber** [comment]
And thanks for the 'okay' workaround :grin: 

Let's see if we can fix the CS transform to avoid that :wink:

**Comment by TheCodez** [comment]
> To me, this looks like you transform the cartesian simulation grid directly to a polar coordinate system (CS).

That's exactly what I'm currently doing. 
Thanks for taking the time to do a little drawing. We should do it this way 👍

**Comment by cbachhuber** [comment]
Ok, cool. I just thought why not directly do this in the simulator? I've quickly (not nice yet) implemented this, see [this commit](https://github.com/cbachhuber/dynamic-occupancy-grid-map/commit/74d9f2f23c3f93bf5b7f1d1c8173a878aa0394d4).

With this, vehicles moving in y-direction are correctly displayed in `grid_img`, they move in  a straight line only in y-direction. Comparing the GT values to the estimated ones looks already very good. However, vehicles with only x-velocity now exhibit the trajectory seen in the right side of my drawing above. I would have expected a straight line parallel to the x-axis.

To reproduce, check out [my branch](https://github.com/cbachhuber/dynamic-occupancy-grid-map/commits/evaluate-performance) and run it. I'm a bit puzzled how this works for the y-velocity case, but not for the x-velocity case.

Could you maybe give me an overview of the coordinate system transformations going on in the demo application on master? I imagine something like

Simulator: cartesian CS
<CS transformation?>
Sensor: polar CS
<CS transformation?>
Grid: cartesian CS?
...

It would be very helpful to me to have something like that, I would appreciate it! :)

**Comment by TheCodez** [comment]
Simulator is using Cartesian.
The sensor is then using this cartesian movement as if it were in polar.
And finally polar to cartesian transformation.

Hope that is helpful :)

One tip is to use the method `compute_raw_polar_measurement_grid_image` to see the sensor grid before the cartesian conversion.

**Comment by cbachhuber** [comment]
Thanks for the swift response! Why does the result from `compute_raw_polar_measurement_grid_image` (basically `grid_map.polar_meas_cell_array`) have a different size (250x100 cells)? Could that be an issue?

> And finally polar to cartesian transformation.

At which point does this happen? Is the raw measurement grid transformed?

**Comment by TheCodez** [comment]
This is intendent but it could be a problem with the calculations. I suggest you to read this https://mediatum.ub.tum.de/doc/1094852/1094852.pdf starting at page 28 for further information.

So basically the bearing size correspond to the number of measurements. This local sensor grid can be used for grid maps of any size.

This is the line were the transformation happens using the texture mapping:
https://github.com/TheCodez/dynamic-occupancy-grid-map/blob/master/dogm/src/dogm.cu#L190

Maybe some calculations have to be scaled to account for the bigger grid map than the sensor grid.

I hope this helps a bit, I'm really confused here myself.

**Comment by cbachhuber** [comment]
Thanks for all the material.

I got it! The issue is that rendering to 120 degrees FoV is a different transform compared to the original cartesian to 180 degrees polar coordinate system. So currently, if you set the FoV to 180 degrees, everything is working fine :)

See my current branch to reconstruct. Let's think about a way to fix this properly. I guess we should (somehow) use the FoV in the simulator's cartesian->polar transform.

**Comment by TheCodez** [comment]
Now that https://github.com/TheCodez/dynamic-occupancy-grid-map/pull/25 is merged it should be a lot easier to do the evaluation 👍

**Comment by cbachhuber** [comment]
Right! There are still two magic conversions involved, but at least they are only linear :laughing:

**Comment by cbachhuber** [comment]
Continuing on this topic, I found an issue in the simulator: The car positions are not at all related to the grid size or resolution. Car positions are only related to `sensor_horizontal_scan_points`. For example, if I reduce `sensor_horizontal_scan_points` from 100 to 80, x-position zero stays at the same position in the sensor measurement, but x-position 80 is now the new rightmost position in the grid. So horizontally, we zoom into the image. In summary, car positions on the gird are changing when I change `sensor_horizontal_scan_points`. I think they shouldn't.

To resolve this, I suggest implementing a module that knows the physical grid size (`grid_params.size`) and maps the vehicle positions in the simulator to points on the measurement vector. This module is also used in the precision_evaluator to map the grid cell coordinates to physical positions again.

What do you think about this?

**Comment by TheCodez** [comment]
Yes ideally all vehicles should relate to a cartesian coordinate system. The simulator measures them and returns them as a list of of range measurements, where each index in the list corresponds to an angle, for an opening angle of 120° and 100 measurements, this would of course be 1.2°. To not miss measurements on the cartesian grid we would probably need more than 100 measurements/rays.

Having such a module sounds like a good idea. This way we should have no error when doing the transformations.

**Comment by cbachhuber** [comment]
What else needs to be done to resolve this issue? More and more extensive testing scenarios?

**Comment by TheCodez** [comment]
Adding more metrics would be cool, such as RMSE and StdDev.

**Comment by cbachhuber** [comment]
I also had the idea of per-target errors. Then you could log signed (not absolute) errors and maybe see systematic issues.
