### ISSUE TITLE
Validate CMake build instructions

### ISSUE THREAD

**Issue by TheCodez** [TheCodez/dynamic-occupancy-grid-map#5]

**Comment by cbachhuber** [comment]
Hi, great work on this project! 

When trying to build this on my machine, I run into two issues in [CMakeLists.txt](https://github.com/TheCodez/dynamic-occupancy-grid-map/blob/master/dogm/CMakeLists.txt):
1. [CUDA_INCLUDE_DIRS](https://github.com/TheCodez/dynamic-occupancy-grid-map/blob/master/dogm/CMakeLists.txt#L40) is not set on my machine. It is suggested to [use CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES](https://stackoverflow.com/a/56198824/7260972) instead. That works for me (CUDA 10.1)
    Does this depend on the CUDA version? Which one are you using?
2. [add_subdirectory(tests)](https://github.com/TheCodez/dynamic-occupancy-grid-map/blob/master/dogm/CMakeLists.txt#L125) tries to find a non-existing directory. Do you either want to push that directory, or remove this line from CMakeLists.txt?

**Comment by TheCodez** [comment]
@cbachhuber 

First of all, thanks for your interest in the project 👍 

To give answers to your points:

1. You're right, `CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES` is the right variable to use here (`CUDA_INCLUDE_DIRS` is probably only set when using the FindCUDA package). I'm also using CUDA 10.1.

2. All test related lines can be removed. It was meant for a test project I never started.

Would you mind sending a pull request? That would be awesome!

**Comment by cbachhuber** [comment]
Sure :+1:
