### ISSUE TITLE
question: classification between dynamic grid vs static grid 

### ISSUE THREAD

**Issue by weidezhang** [TheCodez/dynamic-occupancy-grid-map#60]
Hi
Thanks for the fantastic work. Just curious if you can have dynamic grid vs static grid classification and obstacle clustering logic similar to https://ieeexplore.ieee.org/document/7604119

Thanks,

**Comment by TheCodez** [comment]
Thanks for your interest in the project.

We currently have similiar logic in the demo project. We filter out dynamic cells based on occupancy probability and mahalanobis distance and then cluster those dynamic cells to compare them with our ground truth for evaluation purposes.

See here:
https://github.com/TheCodez/dynamic-occupancy-grid-map/blob/master/dogm/demo/utils/image_creation.cpp#L24

and here:
https://github.com/TheCodez/dynamic-occupancy-grid-map/blob/master/dogm/demo/utils/precision_evaluator.cpp#L29

I'm guessing what you're asking for is a module which receives as input an array of GridCells and returns clustered dynamic cells?
Given the systems we already have this could be implemented as an extra module.

**Comment by weidezhang** [comment]
Thanks a lot for your answer.
