### ISSUE TITLE
Split measurement grid calculation from DOGM class into own class and package

### ISSUE THREAD

**Issue by TheCodez** [TheCodez/dynamic-occupancy-grid-map#8]

**Comment by cbachhuber** [comment]
Adding my 2 cents here: shouldn't the measurement grid be created by the simulator? 

And shouldn't the simulator live inside this repo?

**Comment by TheCodez** [comment]
Sorry for not being specific enough with the issue description.

What I mean is remove the measurement grid calculation from the `DOGM` class. This class should only be responsible for the particle filter and should receive a measurement grid as input each iteration.

My (not really fast) texture mapping measurement grid calculation then lives inside another folder inside this repo and is used by default in the demo.

The goal is to make it possible for others to create their own measurement grid calculation package, e.g. for different sensor types and then just plug their measurement grid into the `DOGM` class. So the overall goal is to make everything more modular.

The simulator is only used to generate fake laser measurements, which are then used to generate the measurement grid using the texture mapping approach, but yes it should stay inside this repo, everything still stays in this repo after all :)

Hope that clears things up.

**Comment by cbachhuber** [comment]
No worries, I understand now. Thanks for the explanation!

What's your plan with the images in folder [build/meas_grids](https://github.com/TheCodez/dynamic-occupancy-grid-map/tree/master/dogm/build/meas_grids)? I saw that class `DOGM` has the option of using those as alternative input. Do you want to keep that?

**Comment by TheCodez** [comment]
I want to remove them in the near future. Until then as long as the build directory is set to `dogm/build`, there's no harm in having them.

Currently using those images as input, the velocity orientation of the bottom object is slightly off. In the comparison project this is correct: https://github.com/TheCodez/dogma

Until this is fixed they should stay for testing.

**Comment by cbachhuber** [comment]
Sounds good, thanks for clarifying! :+1:

**Comment by TheCodez** [comment]
@cbachhuber 

I was thinking of having a `meas_grid_shared` project having a header with the measurement grid struct definition. This allows others to create their own measurement grid generator which produces an array of `MeasurementCell`.

I would also like to add a `texture_map_meas_grid` project which uses the `meas_grid_shared` package and is used as the measurement grid generator of the demo project.

The DOGM project also uses the `meas_grid_shared` package which allows it to have this API 
```cpp
void updateGrid(MeasurementCell* meas_grid, float dt);
```

What do you think about this? Do you know a better way to do this?

**Comment by cbachhuber** [comment]
Let's clarify names: when you talk about a project, you mean a cmake target (i.e. a library or executable), right?

Why don't you call folder `meas_grid_shared` just `grid`? A measurement grid is also a grid, right?

I like having a separate cmake target for the msmt grid calculation from simulation. I suggest naming this folder `simulation`. Inside `simulation`, you have the c++ simulator (e.g. in `simulation/simulator`) that is currently living in `demo` and the grid calculation (e.g. in `simulation/converters/convert_radial_measurements_to_grid.cpp`). What's your opinion about this?

That would allow your proposed API, I'm all for using that.

**Comment by TheCodez** [comment]
> Let's clarify names: when you talk about a project, you mean a cmake target (i.e. a library or executable), right?

Yes exactly.

> Why don't you call folder meas_grid_shared just grid? A measurement grid is also a grid, right?

The meas grid is a grid but given it's extra properties I think I stick to the name `meas_grid`.

> I like having a separate cmake target for the msmt grid calculation from simulation. I suggest naming this folder simulation. Inside simulation, you have the c++ simulator (e.g. in simulation/simulator) that is currently living in demo and the grid calculation (e.g. in simulation/converters/convert_radial_measurements_to_grid.cpp).

Yes something along those lines sounds good. Now the question arises how to design the measurement grid mapper API.
Maybe something like this for a single/multiple layer laser scanner:

```cpp
class LaserMeasurementGrid
{
public:
	LaserMeasurementGrid(const LaserParams& params);
	
    MeasurementCell* generateGrid(const std::vector<float>& measurements);
};
```

For a more advanced LIDAR like Velodynes maybe something like:

```cpp
class LIDARMeasurementGrid
{
public:
	LIDARMeasurementGrid(const LIDARParams& params);
	
    MeasurementCell* generateGrid(const pcl::PCLPointCloud2::ConstPtr& cloud);
};
```

Ideally both should extend some base class. Also both classes should be given the sensor pose and DOGM grid dimensions. The DOGM grid dimensions so that all measurements grids are created with the same size for simplicity. For example a forward facing sensor would create a measurement grid like https://github.com/TheCodez/dynamic-occupancy-grid-map/issues/53. A backwards facing sensor would create a grid with the same dimensions just flipped horizontally and located slightly behind the ego vehicle (based on the defined sensor position).

This would allow the DOGM class to receive a list of measurement grids, which are then fused to a single measurement grid which is used by the particle filter.

What do you think?

**Comment by cbachhuber** [comment]
> The meas grid is a grid but given it's extra properties I think I stick to the name meas_grid.

What are those? Maybe inheriting from a more general base grid makes sense? But I don't want to overthrow everything in one go. We can separate this later.

Yes, I like the suggestion! This is a good way forward :)

**Comment by TheCodez** [comment]
I would say a base grid cell has a mass for free and an occupied mass. The measurement cell also has an association probability and likelihood. The grid cells that are used in the particle filter have some more properties.
However, I would like to not introduce inheritance for those simple CUDA structs :)

**Comment by cbachhuber** [comment]
Agreed, that's not enough justification for separatoin 👍
