### ISSUE TITLE
Question: Why are the particles sampling velocities given to be in m/s

### ISSUE THREAD

**Issue by geoeo** [TheCodez/dynamic-occupancy-grid-map#96]
As far as I understand the particles in the grid live in the grid space (cells). 
But according to the Params structure (comments) the sampling velocities are in m/s?

**Comment by TheCodez** [comment]
Yes, currently particles are in the grid space though it would be better if they were in world space. This [PR](https://github.com/TheCodez/dynamic-occupancy-grid-map/pull/85/commits/28d13ef63b48ac6eeb2c1a2a92cb302313ab5f50) fixes that, but I haven't got around to integrating it yet.
So you're right, the documentation for the param says m/s when in reality it's currently m/s / resolution (same applies to the process noise). I'll try to fix that once I find some time.

**Comment by geoeo** [comment]
Thanks for clearing it up. I was wondering why I had to put higher noise values than would be expected with m/s
